### ISSUE TITLE
startup.cfg is invalid! from trying to load the operating system

### ISSUE THREAD

**Issue by VeryCoolMoment** [fox32-arch/fox32os#1]
I'm not sure why its happening but whenever i try loading the operating system i just get a "startup.cfg is invalid! error"

**Comment by ry755** [comment]
Oops sorry, looks like I need to document this better. That error is normal unless you either mount an FXF binary as the second disk image (by passing it as the second argument to fox32) or by modifying the fox32os disk image and adding a startup.cfg file.

Take a look at the demos repo for some example programs to run, the readme there shows how to run them.

Currently fox32os provides no user interface or anything by default, but in the next release (hopefully coming in the next day or so) there will be an included Launcher application that will provide an interface to launch other applications.
