### ISSUE TITLE
Starting a second terminal and exiting it breaks something

### ISSUE THREAD

**Issue by neuschaefer** [fox32-arch/fox32os#3]
How to reproduce:

- Start fox32 with fox32os
- enter `terminal` in the terminal
  - a second terminal pops up
- enter `exit` in the new terminal
  - the second terminal is now closed, but the first one doesn't return to the command prompt

![term](https://user-images.githubusercontent.com/1021512/213719262-d91983ab-4c7e-4e9b-bcf3-7d4c986b25c0.png)

**Comment by ry755** [comment]
Yeah I've noticed this too, off the top of my head I'm not sure what would be causing this. Another interesting thing is that by starting a new terminal without suspending the current shell (type `*terminal`), then all key presses in the newly opened terminal are doubled. There's likely something weird going on with fox32os's VFS streams, I'll have to take a closer look.

**Comment by ry755** [comment]
Alright I looked into it and I realized that this happens because all instances of the shell (which is built into the kernel) shares the same state. I don't know how I didn't realize this sooner :P This will take some rewriting.

**Comment by ry755** [comment]
Fixed in 9e256a7e3caef349c7150d9afc2ebc4246211d69.
