### ISSUE TITLE
Running `dir` on an empty disk prints garbage

### ISSUE THREAD

**Issue by neuschaefer** [fox32-arch/fox32os#8]
![dir1](https://user-images.githubusercontent.com/1021512/215554962-d4223e02-4ac9-4358-a09d-dd0100f70481.png)
![dir2](https://user-images.githubusercontent.com/1021512/215554968-54ad8428-3fab-41d6-bb9a-4f747d624c3e.png)

(To get to this point, it is first necessary to boot fox32os with an addition disk attached without running it as an FXF file; I have an unfinished patchset for that)

**Comment by ry755** [comment]
What do you mean by "empty disk"? Is this a file containing all zeros? Or a blank RYFS disk?

**Comment by neuschaefer** [comment]
Yep, a RYFS disk without any files.

**Comment by ry755** [comment]
Fixed in 2a8eb5b267b243af42e755233f2e761a38692ece.
